info:
  contact: {}
paths:
  /api/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: userID
        in: query
        name: name
        type: string
      - description: telephone
        in: query
        name: telephone
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 注册
swagger: "2.0"
